**Practical No.4, Roll no.:- S031,**
**Class:- SYIT,**
**Date of Submission:- 5-8-26,**
**Date of Assignment:- 5-8-26**
**Numpy**

**Panvir Rao, S031**

In [12]:
import numpy as np

Q1. Write a python code to create Numpy Array.


In [13]:
a=np.array([0,1,2,3])
print(a)

[0 1 2 3]


Q2. Write a python code to demonstrate basic operations on single array.


In [14]:
print(a+2)
print(a*2)
print(a-2)

[2 3 4 5]
[0 2 4 6]
[-2 -1  0  1]


Q3. Write a python code to create array with 10 elements and slice element from 1st to 5th element.


In [15]:
b=np.array([0,1,2,3,4,5,6,7,8,9])
print(b[:5])

[0 1 2 3 4]


Q4. Write a python code to sort an array alphabetically.


In [16]:
c=np.array(["Banana","Apple","Chickoo","Mango"])
np.sort(c)

array(['Apple', 'Banana', 'Chickoo', 'Mango'], dtype='<U7')

Q5. Write a python code to create a filter array that will return maximum values from an array.


In [17]:
d=np.array([100,1000,55000])
print(d[d>100])

[ 1000 55000]
